# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dongchen/Documents/caer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dongchen/Documents/caer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dongchen/Documents/caer/CMakeFiles /home/dongchen/Documents/caer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dongchen/Documents/caer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named caer-bin

# Build rule for target.
caer-bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 caer-bin
.PHONY : caer-bin

# fast build rule for target.
caer-bin/fast:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/build
.PHONY : caer-bin/fast

#=============================================================================
# Target rules for targets named bafilter

# Build rule for target.
bafilter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bafilter
.PHONY : bafilter

# fast build rule for target.
bafilter/fast:
	$(MAKE) -f modules/backgroundactivityfilter/CMakeFiles/bafilter.dir/build.make modules/backgroundactivityfilter/CMakeFiles/bafilter.dir/build
.PHONY : bafilter/fast

#=============================================================================
# Target rules for targets named frameenhancer

# Build rule for target.
frameenhancer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 frameenhancer
.PHONY : frameenhancer

# fast build rule for target.
frameenhancer/fast:
	$(MAKE) -f modules/frameenhancer/CMakeFiles/frameenhancer.dir/build.make modules/frameenhancer/CMakeFiles/frameenhancer.dir/build
.PHONY : frameenhancer/fast

#=============================================================================
# Target rules for targets named dvs128

# Build rule for target.
dvs128: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dvs128
.PHONY : dvs128

# fast build rule for target.
dvs128/fast:
	$(MAKE) -f modules/ini/CMakeFiles/dvs128.dir/build.make modules/ini/CMakeFiles/dvs128.dir/build
.PHONY : dvs128/fast

#=============================================================================
# Target rules for targets named davis

# Build rule for target.
davis: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 davis
.PHONY : davis

# fast build rule for target.
davis/fast:
	$(MAKE) -f modules/ini/CMakeFiles/davis.dir/build.make modules/ini/CMakeFiles/davis.dir/build
.PHONY : davis/fast

#=============================================================================
# Target rules for targets named dynapse

# Build rule for target.
dynapse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dynapse
.PHONY : dynapse

# fast build rule for target.
dynapse/fast:
	$(MAKE) -f modules/ini/CMakeFiles/dynapse.dir/build.make modules/ini/CMakeFiles/dynapse.dir/build
.PHONY : dynapse/fast

#=============================================================================
# Target rules for targets named edvs

# Build rule for target.
edvs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 edvs
.PHONY : edvs

# fast build rule for target.
edvs/fast:
	$(MAKE) -f modules/ini/CMakeFiles/edvs.dir/build.make modules/ini/CMakeFiles/edvs.dir/build
.PHONY : edvs/fast

#=============================================================================
# Target rules for targets named input_file

# Build rule for target.
input_file: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 input_file
.PHONY : input_file

# fast build rule for target.
input_file/fast:
	$(MAKE) -f modules/misc/in/CMakeFiles/input_file.dir/build.make modules/misc/in/CMakeFiles/input_file.dir/build
.PHONY : input_file/fast

#=============================================================================
# Target rules for targets named input_net_tcp_client

# Build rule for target.
input_net_tcp_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 input_net_tcp_client
.PHONY : input_net_tcp_client

# fast build rule for target.
input_net_tcp_client/fast:
	$(MAKE) -f modules/misc/in/CMakeFiles/input_net_tcp_client.dir/build.make modules/misc/in/CMakeFiles/input_net_tcp_client.dir/build
.PHONY : input_net_tcp_client/fast

#=============================================================================
# Target rules for targets named input_net_socket_client

# Build rule for target.
input_net_socket_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 input_net_socket_client
.PHONY : input_net_socket_client

# fast build rule for target.
input_net_socket_client/fast:
	$(MAKE) -f modules/misc/in/CMakeFiles/input_net_socket_client.dir/build.make modules/misc/in/CMakeFiles/input_net_socket_client.dir/build
.PHONY : input_net_socket_client/fast

#=============================================================================
# Target rules for targets named output_net_udp

# Build rule for target.
output_net_udp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 output_net_udp
.PHONY : output_net_udp

# fast build rule for target.
output_net_udp/fast:
	$(MAKE) -f modules/misc/out/CMakeFiles/output_net_udp.dir/build.make modules/misc/out/CMakeFiles/output_net_udp.dir/build
.PHONY : output_net_udp/fast

#=============================================================================
# Target rules for targets named output_net_tcp_client

# Build rule for target.
output_net_tcp_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 output_net_tcp_client
.PHONY : output_net_tcp_client

# fast build rule for target.
output_net_tcp_client/fast:
	$(MAKE) -f modules/misc/out/CMakeFiles/output_net_tcp_client.dir/build.make modules/misc/out/CMakeFiles/output_net_tcp_client.dir/build
.PHONY : output_net_tcp_client/fast

#=============================================================================
# Target rules for targets named output_net_tcp_server

# Build rule for target.
output_net_tcp_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 output_net_tcp_server
.PHONY : output_net_tcp_server

# fast build rule for target.
output_net_tcp_server/fast:
	$(MAKE) -f modules/misc/out/CMakeFiles/output_net_tcp_server.dir/build.make modules/misc/out/CMakeFiles/output_net_tcp_server.dir/build
.PHONY : output_net_tcp_server/fast

#=============================================================================
# Target rules for targets named output_net_socket_server

# Build rule for target.
output_net_socket_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 output_net_socket_server
.PHONY : output_net_socket_server

# fast build rule for target.
output_net_socket_server/fast:
	$(MAKE) -f modules/misc/out/CMakeFiles/output_net_socket_server.dir/build.make modules/misc/out/CMakeFiles/output_net_socket_server.dir/build
.PHONY : output_net_socket_server/fast

#=============================================================================
# Target rules for targets named output_file

# Build rule for target.
output_file: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 output_file
.PHONY : output_file

# fast build rule for target.
output_file/fast:
	$(MAKE) -f modules/misc/out/CMakeFiles/output_file.dir/build.make modules/misc/out/CMakeFiles/output_file.dir/build
.PHONY : output_file/fast

#=============================================================================
# Target rules for targets named output_net_socket_client

# Build rule for target.
output_net_socket_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 output_net_socket_client
.PHONY : output_net_socket_client

# fast build rule for target.
output_net_socket_client/fast:
	$(MAKE) -f modules/misc/out/CMakeFiles/output_net_socket_client.dir/build.make modules/misc/out/CMakeFiles/output_net_socket_client.dir/build
.PHONY : output_net_socket_client/fast

#=============================================================================
# Target rules for targets named statistics

# Build rule for target.
statistics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 statistics
.PHONY : statistics

# fast build rule for target.
statistics/fast:
	$(MAKE) -f modules/statistics/CMakeFiles/statistics.dir/build.make modules/statistics/CMakeFiles/statistics.dir/build
.PHONY : statistics/fast

#=============================================================================
# Target rules for targets named visualizer

# Build rule for target.
visualizer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 visualizer
.PHONY : visualizer

# fast build rule for target.
visualizer/fast:
	$(MAKE) -f modules/visualizer/CMakeFiles/visualizer.dir/build.make modules/visualizer/CMakeFiles/visualizer.dir/build
.PHONY : visualizer/fast

#=============================================================================
# Target rules for targets named meanratefilter

# Build rule for target.
meanratefilter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 meanratefilter
.PHONY : meanratefilter

# fast build rule for target.
meanratefilter/fast:
	$(MAKE) -f modules/meanratefilter/CMakeFiles/meanratefilter.dir/build.make modules/meanratefilter/CMakeFiles/meanratefilter.dir/build
.PHONY : meanratefilter/fast

#=============================================================================
# Target rules for targets named synapsereconfig

# Build rule for target.
synapsereconfig: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 synapsereconfig
.PHONY : synapsereconfig

# fast build rule for target.
synapsereconfig/fast:
	$(MAKE) -f modules/synapsereconfig/CMakeFiles/synapsereconfig.dir/build.make modules/synapsereconfig/CMakeFiles/synapsereconfig.dir/build
.PHONY : synapsereconfig/fast

#=============================================================================
# Target rules for targets named fpgaspikegen

# Build rule for target.
fpgaspikegen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fpgaspikegen
.PHONY : fpgaspikegen

# fast build rule for target.
fpgaspikegen/fast:
	$(MAKE) -f modules/fpgaspikegen/CMakeFiles/fpgaspikegen.dir/build.make modules/fpgaspikegen/CMakeFiles/fpgaspikegen.dir/build
.PHONY : fpgaspikegen/fast

#=============================================================================
# Target rules for targets named softspikegen

# Build rule for target.
softspikegen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 softspikegen
.PHONY : softspikegen

# fast build rule for target.
softspikegen/fast:
	$(MAKE) -f modules/softspikegen/CMakeFiles/softspikegen.dir/build.make modules/softspikegen/CMakeFiles/softspikegen.dir/build
.PHONY : softspikegen/fast

#=============================================================================
# Target rules for targets named poissonspikegen

# Build rule for target.
poissonspikegen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 poissonspikegen
.PHONY : poissonspikegen

# fast build rule for target.
poissonspikegen/fast:
	$(MAKE) -f modules/poissonspikegen/CMakeFiles/poissonspikegen.dir/build.make modules/poissonspikegen/CMakeFiles/poissonspikegen.dir/build
.PHONY : poissonspikegen/fast

#=============================================================================
# Target rules for targets named localfiltdownsample

# Build rule for target.
localfiltdownsample: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 localfiltdownsample
.PHONY : localfiltdownsample

# fast build rule for target.
localfiltdownsample/fast:
	$(MAKE) -f modules/localfiltdownsample/CMakeFiles/localfiltdownsample.dir/build.make modules/localfiltdownsample/CMakeFiles/localfiltdownsample.dir/build
.PHONY : localfiltdownsample/fast

#=============================================================================
# Target rules for targets named dsnn

# Build rule for target.
dsnn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dsnn
.PHONY : dsnn

# fast build rule for target.
dsnn/fast:
	$(MAKE) -f modules/dsnn/CMakeFiles/dsnn.dir/build.make modules/dsnn/CMakeFiles/dsnn.dir/build
.PHONY : dsnn/fast

#=============================================================================
# Target rules for targets named caer-ctl

# Build rule for target.
caer-ctl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 caer-ctl
.PHONY : caer-ctl

# fast build rule for target.
caer-ctl/fast:
	$(MAKE) -f utils/caerctl/CMakeFiles/caer-ctl.dir/build.make utils/caerctl/CMakeFiles/caer-ctl.dir/build
.PHONY : caer-ctl/fast

#=============================================================================
# Target rules for targets named tcpststat

# Build rule for target.
tcpststat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tcpststat
.PHONY : tcpststat

# fast build rule for target.
tcpststat/fast:
	$(MAKE) -f utils/tcpststat/CMakeFiles/tcpststat.dir/build.make utils/tcpststat/CMakeFiles/tcpststat.dir/build
.PHONY : tcpststat/fast

#=============================================================================
# Target rules for targets named udpststat

# Build rule for target.
udpststat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 udpststat
.PHONY : udpststat

# fast build rule for target.
udpststat/fast:
	$(MAKE) -f utils/udpststat/CMakeFiles/udpststat.dir/build.make utils/udpststat/CMakeFiles/udpststat.dir/build
.PHONY : udpststat/fast

#=============================================================================
# Target rules for targets named unixststat

# Build rule for target.
unixststat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unixststat
.PHONY : unixststat

# fast build rule for target.
unixststat/fast:
	$(MAKE) -f utils/unixststat/CMakeFiles/unixststat.dir/build.make utils/unixststat/CMakeFiles/unixststat.dir/build
.PHONY : unixststat/fast

base/config.o: base/config.cpp.o

.PHONY : base/config.o

# target to build an object file
base/config.cpp.o:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/base/config.cpp.o
.PHONY : base/config.cpp.o

base/config.i: base/config.cpp.i

.PHONY : base/config.i

# target to preprocess a source file
base/config.cpp.i:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/base/config.cpp.i
.PHONY : base/config.cpp.i

base/config.s: base/config.cpp.s

.PHONY : base/config.s

# target to generate assembly for a file
base/config.cpp.s:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/base/config.cpp.s
.PHONY : base/config.cpp.s

base/config_server.o: base/config_server.cpp.o

.PHONY : base/config_server.o

# target to build an object file
base/config_server.cpp.o:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/base/config_server.cpp.o
.PHONY : base/config_server.cpp.o

base/config_server.i: base/config_server.cpp.i

.PHONY : base/config_server.i

# target to preprocess a source file
base/config_server.cpp.i:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/base/config_server.cpp.i
.PHONY : base/config_server.cpp.i

base/config_server.s: base/config_server.cpp.s

.PHONY : base/config_server.s

# target to generate assembly for a file
base/config_server.cpp.s:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/base/config_server.cpp.s
.PHONY : base/config_server.cpp.s

base/log.o: base/log.c.o

.PHONY : base/log.o

# target to build an object file
base/log.c.o:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/base/log.c.o
.PHONY : base/log.c.o

base/log.i: base/log.c.i

.PHONY : base/log.i

# target to preprocess a source file
base/log.c.i:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/base/log.c.i
.PHONY : base/log.c.i

base/log.s: base/log.c.s

.PHONY : base/log.s

# target to generate assembly for a file
base/log.c.s:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/base/log.c.s
.PHONY : base/log.c.s

base/mainloop.o: base/mainloop.cpp.o

.PHONY : base/mainloop.o

# target to build an object file
base/mainloop.cpp.o:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/base/mainloop.cpp.o
.PHONY : base/mainloop.cpp.o

base/mainloop.i: base/mainloop.cpp.i

.PHONY : base/mainloop.i

# target to preprocess a source file
base/mainloop.cpp.i:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/base/mainloop.cpp.i
.PHONY : base/mainloop.cpp.i

base/mainloop.s: base/mainloop.cpp.s

.PHONY : base/mainloop.s

# target to generate assembly for a file
base/mainloop.cpp.s:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/base/mainloop.cpp.s
.PHONY : base/mainloop.cpp.s

base/misc.o: base/misc.c.o

.PHONY : base/misc.o

# target to build an object file
base/misc.c.o:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/base/misc.c.o
.PHONY : base/misc.c.o

base/misc.i: base/misc.c.i

.PHONY : base/misc.i

# target to preprocess a source file
base/misc.c.i:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/base/misc.c.i
.PHONY : base/misc.c.i

base/misc.s: base/misc.c.s

.PHONY : base/misc.s

# target to generate assembly for a file
base/misc.c.s:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/base/misc.c.s
.PHONY : base/misc.c.s

base/module.o: base/module.cpp.o

.PHONY : base/module.o

# target to build an object file
base/module.cpp.o:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/base/module.cpp.o
.PHONY : base/module.cpp.o

base/module.i: base/module.cpp.i

.PHONY : base/module.i

# target to preprocess a source file
base/module.cpp.i:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/base/module.cpp.i
.PHONY : base/module.cpp.i

base/module.s: base/module.cpp.s

.PHONY : base/module.s

# target to generate assembly for a file
base/module.cpp.s:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/base/module.cpp.s
.PHONY : base/module.cpp.s

ext/sshs/sshs.o: ext/sshs/sshs.cpp.o

.PHONY : ext/sshs/sshs.o

# target to build an object file
ext/sshs/sshs.cpp.o:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/ext/sshs/sshs.cpp.o
.PHONY : ext/sshs/sshs.cpp.o

ext/sshs/sshs.i: ext/sshs/sshs.cpp.i

.PHONY : ext/sshs/sshs.i

# target to preprocess a source file
ext/sshs/sshs.cpp.i:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/ext/sshs/sshs.cpp.i
.PHONY : ext/sshs/sshs.cpp.i

ext/sshs/sshs.s: ext/sshs/sshs.cpp.s

.PHONY : ext/sshs/sshs.s

# target to generate assembly for a file
ext/sshs/sshs.cpp.s:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/ext/sshs/sshs.cpp.s
.PHONY : ext/sshs/sshs.cpp.s

ext/sshs/sshs_helper.o: ext/sshs/sshs_helper.cpp.o

.PHONY : ext/sshs/sshs_helper.o

# target to build an object file
ext/sshs/sshs_helper.cpp.o:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/ext/sshs/sshs_helper.cpp.o
.PHONY : ext/sshs/sshs_helper.cpp.o

ext/sshs/sshs_helper.i: ext/sshs/sshs_helper.cpp.i

.PHONY : ext/sshs/sshs_helper.i

# target to preprocess a source file
ext/sshs/sshs_helper.cpp.i:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/ext/sshs/sshs_helper.cpp.i
.PHONY : ext/sshs/sshs_helper.cpp.i

ext/sshs/sshs_helper.s: ext/sshs/sshs_helper.cpp.s

.PHONY : ext/sshs/sshs_helper.s

# target to generate assembly for a file
ext/sshs/sshs_helper.cpp.s:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/ext/sshs/sshs_helper.cpp.s
.PHONY : ext/sshs/sshs_helper.cpp.s

ext/sshs/sshs_node.o: ext/sshs/sshs_node.cpp.o

.PHONY : ext/sshs/sshs_node.o

# target to build an object file
ext/sshs/sshs_node.cpp.o:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/ext/sshs/sshs_node.cpp.o
.PHONY : ext/sshs/sshs_node.cpp.o

ext/sshs/sshs_node.i: ext/sshs/sshs_node.cpp.i

.PHONY : ext/sshs/sshs_node.i

# target to preprocess a source file
ext/sshs/sshs_node.cpp.i:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/ext/sshs/sshs_node.cpp.i
.PHONY : ext/sshs/sshs_node.cpp.i

ext/sshs/sshs_node.s: ext/sshs/sshs_node.cpp.s

.PHONY : ext/sshs/sshs_node.s

# target to generate assembly for a file
ext/sshs/sshs_node.cpp.s:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/ext/sshs/sshs_node.cpp.s
.PHONY : ext/sshs/sshs_node.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/caer-bin.dir/build.make CMakeFiles/caer-bin.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... caer-bin"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... edit_cache"
	@echo "... bafilter"
	@echo "... frameenhancer"
	@echo "... dvs128"
	@echo "... davis"
	@echo "... dynapse"
	@echo "... edvs"
	@echo "... input_file"
	@echo "... input_net_tcp_client"
	@echo "... input_net_socket_client"
	@echo "... output_net_udp"
	@echo "... output_net_tcp_client"
	@echo "... output_net_tcp_server"
	@echo "... output_net_socket_server"
	@echo "... output_file"
	@echo "... output_net_socket_client"
	@echo "... statistics"
	@echo "... visualizer"
	@echo "... meanratefilter"
	@echo "... synapsereconfig"
	@echo "... fpgaspikegen"
	@echo "... softspikegen"
	@echo "... poissonspikegen"
	@echo "... localfiltdownsample"
	@echo "... dsnn"
	@echo "... caer-ctl"
	@echo "... tcpststat"
	@echo "... udpststat"
	@echo "... unixststat"
	@echo "... base/config.o"
	@echo "... base/config.i"
	@echo "... base/config.s"
	@echo "... base/config_server.o"
	@echo "... base/config_server.i"
	@echo "... base/config_server.s"
	@echo "... base/log.o"
	@echo "... base/log.i"
	@echo "... base/log.s"
	@echo "... base/mainloop.o"
	@echo "... base/mainloop.i"
	@echo "... base/mainloop.s"
	@echo "... base/misc.o"
	@echo "... base/misc.i"
	@echo "... base/misc.s"
	@echo "... base/module.o"
	@echo "... base/module.i"
	@echo "... base/module.s"
	@echo "... ext/sshs/sshs.o"
	@echo "... ext/sshs/sshs.i"
	@echo "... ext/sshs/sshs.s"
	@echo "... ext/sshs/sshs_helper.o"
	@echo "... ext/sshs/sshs_helper.i"
	@echo "... ext/sshs/sshs_helper.s"
	@echo "... ext/sshs/sshs_node.o"
	@echo "... ext/sshs/sshs_node.i"
	@echo "... ext/sshs/sshs_node.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

