cp caer-config-backup.xml caer-config.xml

make clean

rm -rf CMakeFiles
rm caer-bin
rm CMakeCache.txt

cmake -DCMAKE_BUILD_TYPE=Debug -DDVS128=1 -DEDVS=1 -DDAVIS=1 -DDYNAPSE=1 -DBAFILTER=1 -DFRAMEENHANCER=1 -DCAMERACALIBRATION=0 -DSTATISTICS=1  -DVISUALIZER=1 -DINPUT_FILE=1 -DOUTPUT_FILE=1 -DINPUT_NETWORK=1 -DOUTPUT_NETWORK=1 -DROTATE=1 -DMEANRATEFILTER=1 -DSYNAPSERECONFIG=1 -DFPGASPIKEGEN=1 -DPOISSONSPIKEGEN=1 -DLOCALFILTDOWNSAMPLE=1 -DDSNN=1 -DSOFTSPIKEGEN=1 .

make -j 8
sudo make install

#./caer-bin
